trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'github-container-registry'
  imageRepository: 'excel-pdf-values-validator'
  containerRegistry: 'ghcr.io'
  dockerfilePath: 'fastapi/Dockerfile'
  tag: '$(Build.BuildId)'
  gitHubUsername: '$(GITHUB_USERNAME)'
  gitHubToken: '$(GITHUB_TOKEN)'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        steps:
          - task: DockerInstaller@0

          - task: Docker@2
            displayName: Build and push image
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              command: buildAndPush
              Dockerfile: $(dockerfilePath)
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy to Oracle VM
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'

          - task: SSH@0
            inputs:
              sshEndpoint: 'oracle-ssh-vm'
              runOptions: 'commands'
              commands: |
                docker stop ai-validator || true
                docker rm ai-validator || true
                docker pull $(containerRegistry)/$(imageRepository):$(tag)
                docker-compose -f /home/ubuntu/docker-compose.yml up -d
              workingDirectory: '/home/ubuntu'
